
<section class="content">
   <div class="box box-success">
      <div class="box-header">
        <i class="fa fa-comments-o"></i>

        <h3 class="box-title">GuestBook</h3>

        <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
          <div class="btn-group" data-toggle="btn-toggle">
            <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"> 新增留言</i>
            </button>
          </div>
        </div>
      </div>
      <div class="box-body chat" id="chat-box">

        <?php foreach ($guestbookList as $guestbook) { ?>
     
        <div class="item">
          <img src="dist/img/user3-128x128.jpg" alt="user image" class="offline">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> <?php echo $guestbook->createTime; ?></small>
              Alexander Pierce
            </a>
            <?php echo $guestbook->message; ?>
          </p>
        <!-- 回覆開始-->
        <?php if ($guestbook->replyCount >0) { 
          foreach ($replyList as $reply) {
            
          }
          ?>

           <div class="attachment">
            <h4>Attachments:</h4>

            <p class="filename">
              1-1
            </p>

            <div class="pull-right">
              <button type="button" class="btn btn-primary btn-sm btn-flat">刪除</button>
            </div>
          </div>
        <?php } ?>


        </div>




        <?php }?>


        <!-- chat item -->
        
         
          <div class="attachment">
            <h4>Attachments:</h4>

            <p class="filename">
              1-2
            </p>

            <div class="pull-right">
              <button type="button" class="btn btn-primary btn-sm btn-flat">刪除</button>
            </div>
          </div>
          <!-- /.attachment -->
        </div>
        <!-- /.item -->


        <!-- chat item -->
        <div class="item">
          <img src="dist/img/user3-128x128.jpg" alt="user image" class="offline">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
              Alexander Pierce
            </a>
            2
          </p>
        </div>
        <!-- /.item -->

        <!-- chat item -->
        <div class="item">
          <img src="dist/img/user2-160x160.jpg" alt="user image" class="offline">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:30</small>
              Susan Doe
            </a>
            3
          </p>
        </div>
        <!-- /.item -->
      </div>
      <!-- /.chat -->
    </div>

