
<!DOCTYPE html>
<html>
<section class="content">
   <div class="box box-success">
      <div class="box-header">
        <i class="fa fa-comments-o"></i>

        <h3 class="box-title">GuestBook</h3>

        <div class="box-tools pull-right" data-toggle="tooltip" title="Status">
          <div class="btn-group" data-toggle="btn-toggle">
            <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"> 新增留言</i>
            </button>
          </div>
        </div>
      </div>
      <div class="box-body chat" id="chat-box">
        <!-- chat item -->
        <div class="item">
          <img src="dist/img/user4-128x128.jpg" alt="user image" class="online">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
              Mike Doe
            </a>
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
          </p>
          <div class="attachment">
            <h4>Attachments:</h4>

            <p class="filename">
              Theme-thumbnail-image.jpg
            </p>

            <div class="pull-right">
              <button type="button" class="btn btn-primary btn-sm btn-flat">刪除</button>
            </div>
          </div>
          <div class="attachment">
            <h4>Attachments:</h4>

            <p class="filename">
              Theme-thumbnail-image.jpg
            </p>

            <div class="pull-right">
              <button type="button" class="btn btn-primary btn-sm btn-flat">刪除</button>
            </div>
          </div>
          <!-- /.attachment -->
        </div>
        <!-- /.item -->
        <!-- chat item -->
        <div class="item">
          <img src="dist/img/user3-128x128.jpg" alt="user image" class="offline">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
              Alexander Pierce
            </a>
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
          </p>
        </div>
        <!-- /.item -->
        <!-- chat item -->
        <div class="item">
          <img src="dist/img/user2-160x160.jpg" alt="user image" class="offline">

          <p class="message">
            <a href="#" class="name">
              <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:30</small>
              Susan Doe
            </a>
            I would like to meet you to discuss the latest news about
            the arrival of the new theme. They say it is going to be one the
            best themes on the market
          </p>
        </div>
        <!-- /.item -->
      </div>
      <!-- /.chat -->
    </div>
</div>
<!-- jQuery 3 -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>
