
<!DOCTYPE html>
<html>

<section class="content">
  <!-- general form elements -->
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">留言</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form action="Message.html" method="post">
      <div class="box-body">
        <div class="form-group">
          <label for="exampleInputPassword1">姓名</label>
          <input type="text" class="form-control" id="name">
        </div>
        <div class="form-group">
          <label>留言訊息</label>
          <textarea class="form-control" rows="3" placeholder="Enter ..."></textarea>
        </div>
      </div>
      <!-- /.box-body -->

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
  <!-- /.box -->
    </section>
</div>
<!-- jQuery 3 -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>
